# Day Mode Configuration

# Date range
date:
  start_date: "2024-09-20"
  end_date: "2024-09-20"

# Processing Parameters
processing:
  chunk_size: 5
  max_workers: 1
  enable_parallel: false

# Data Filtering
filter:
  limit_tickers: null  # Process all tickers
  min_periods: 5       # Minimum number of periods required

# Feature Selection
feature_selection:
  method: "shap_threshold"
  min_threshold: 0.01
  min_features: 10
  max_features: 40
  cumulative_threshold: 0.95

# Model Parameters
model:
  type: "elasticnet"
  cv_folds: 5
  test_size: 0.2

# Output
output:
  save_intermediate: true
  results_dir: "results/day_mode"
  visualizations: true 