# Week Mode Configuration

# Date range
date:
  start_date: "2024-09-14"
  end_date: "2024-09-20"

# Processing Parameters
processing:
  chunk_size: 10
  max_workers: 2
  enable_parallel: true

# Data Filtering
filter:
  limit_tickers: 200    # Limit to top 200 tickers by market cap
  min_periods: 5        # Minimum number of periods required

# Feature Selection
feature_selection:
  method: "shap_threshold"
  min_threshold: 0.01
  min_features: 15
  max_features: 50
  cumulative_threshold: 0.95

# Model Parameters
model:
  type: "elasticnet"
  cv_folds: 5
  test_size: 0.2

# Output
output:
  save_intermediate: true
  results_dir: "results/week_mode"
  visualizations: true 